### ISSUE TITLE
How to send events?

### ISSUE THREAD

**Issue by Praveena0989** [mongoose-os-libs/azure#2]
In the doc section for Azure  I can only see device twin update but how to sent telemetry data?

**Comment by rojer** [comment]
[mgos_azure_send_d2c_msg(mg_mk_str(""), mg_mk_str("foo"))](https://github.com/mongoose-os-libs/azure/blob/1cc36cc63b8f77fe7275037c2dc04dde3a25722d/include/mgos_azure.h#L55) in C or [Azure.sendD2CMsg("", "foo")](https://github.com/mongoose-os-libs/azure/blob/1cc36cc63b8f77fe7275037c2dc04dde3a25722d/mjs_fs/api_azure.js#L8) in JS.
